### PR TITLE
working linux port.

### PR DESCRIPTION
**Pull request by advaithm**

### CODE REVIEW

**Comment by lionloya** [comment]
Hi @advaithm 

Thanks for helping me out on this port. Please let me know when you think is ready.

**Comment by advaithm** [comment]
It's ready you can merge it

**Comment by advaithm** [comment]
This also fixes the issue where links in a pdf open in the app instead of the system browser.

**Comment by lionloya** [comment]
Cool man I review it and include it today. Thank you very much

**Pull request merged**
